### ISSUE TITLE
DuneEdit2: inconvenient scrollbars, especially the ones of dropdown lists

### ISSUE THREAD

**Issue by Dmitri-Fatkin** [maximilien-noal/OpenRakis#26]
If it's possible, please make scrollbars of dropdown lists fully-visible right after the very first click. It's necessary to move mouse cursor to scrollbar's placement area at the moment for the element to get fully-revealed. The other scrollbars, for example, in the Map of Dune, are affected by this issue too.

**Comment by maximilien-noal** [comment]
Fixed !
